# Generated by Django 6.0.4 on 2026-04-29 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='master_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
